Competition Tournament/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Competition_Tournament.Data;
using Competition_Tournament.Models;
using Microsoft.EntityFrameworkCore.Query;
using System.Globalization;

namespace Competition_Tournament.Controllers
{
    public class GamesController : Controller
    {
        private readonly CompetitionManagementContext _context;

        public GamesController(CompetitionManagementContext context)
        {
            _context = context;
        }

        // GET: Games
        public async Task<IActionResult> Index(int? competitionId)
        {
            IQueryable<Game> games = _context.Games.Include(g => g.Competition).Include(g => g.Team1).Include(g => g.Team2);

            if (competitionId != null)
            {
                games = games.Where(g => g.CompetitionId == competitionId);
            }

            ViewData["Competitions"] = new SelectList(_context.Competitions, "Id", "Name");

            return View(await games.ToListAsync());
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Games == null)
            {
                return NotFound();
            }

            var game = await _context.Games
                .Include(g => g.Competition)
                .Include(g => g.Team1)
                .Include(g => g.Team2)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // GET: Games/Create
        public IActionResult Create(int? id)
        {
            var competition = _context.Competitions.Include(c => c.Teams).FirstOrDefault(g => g.Id == id);
            if(competition == null) { return NotFound(); }
            ViewData["id"] = id;
            ViewBag.CompetitionName = _context.Competitions.Where(c => c.Id == id)?.FirstOrDefault().Name;
            ViewData["CompetitionId"] = new SelectList(_context.Competitions, "Id", "Name");
            ViewData["Team1Id"] = new SelectList(_context.Teams.Where(t => t.Competitions.Any(c => c.Id == id)), "Id", "Name");
            ViewData["Team2Id"] = new SelectList(_context.Teams.Where(t => t.Competitions.Any(c => c.Id == id)), "Id", "Name");
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Team1Id,Team2Id,Team1Goals,Team2Goals,Team1Name,Team2Name,CompetitionId,Date,Stadium")] Game game, int CompId)
        {
            var competition = _context.Competitions.Include(c => c.CompetitionTypeNavigation).Include(c => c.Teams).Where(g => g.Id == CompId).FirstOrDefault();
            var competition1 = _context.Competitions.Find(game.CompetitionId);
            if (game.Team1Id == game.Team2Id)
            {
                ModelState.AddModelError(string.Empty, "You cannot add a game between two similar teams.");
            }
            else if (competition.CompetitionTypeNavigation.Name == "Knockout")
            {
                if (_context.Games.FirstOrDefault(g => g.CompetitionId == CompId && ((g.Team1Id == game.Team1Id && g.Team2Id == game.Team2Id) || (g.Team1Id == game.Team2Id && g.Team2Id == game.Team1Id)) && g.Id != game.Id) != null)
                {
                    ModelState.AddModelError(string.Empty, "A game between these two teams already exists in this knockout competition.");
                }
                else if(game.Team1Goals == game.Team2Goals && game.Team1Goals != null && game.Team2Goals != null)
                {
                    ModelState.AddModelError(string.Empty, "You can not have ties in a knockout competition");
                }
                else if (game.Date != null && competition != null && competition.StartDate != null && competition.EndDate != null)
                {
                    if (game.Date.Value.Date < competition.StartDate.Value.Date || game.Date.Value.Date > competition.EndDate.Value.Date)
                    {
                        string dateStart = competition.StartDate.Value.Date.ToString("d", CultureInfo.InvariantCulture);
                        string dateEnd = competition.EndDate.Value.Date.ToString("d", CultureInfo.InvariantCulture);
                        ModelState.AddModelError("Date", "The game's date must be between the competition's start and end date: "
                            + dateStart + " - " + dateEnd);
                    }
                }
            }
            else if (game.Date != null && competition != null && competition.StartDate != null && competition.EndDate != null)
            {
                if (game.Date.Value.Date < competition.StartDate.Value.Date || game.Date.Value.Date > competition.EndDate.Value.Date)
                {
                    string dateStart = competition.StartDate.Value.Date.ToString("d", CultureInfo.InvariantCulture);
                    string dateEnd = competition.EndDate.Value.Date.ToString("d", CultureInfo.InvariantCulture);
                    ModelState.AddModelError("Date", "The game's date must be between the competition's start and end date: "
                        + dateStart + " - " + dateEnd);
                }
            }

            if (ModelState.IsValid)
            {
                game.Team1Name = _context.Teams.Find(game.Team1Id).Name;
                game.Team2Name = _context.Teams.Find(game.Team2Id).Name;
                game.CompetitionId = CompId;
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Competitions", new { id = game.CompetitionId });
            }

            ViewData["CompetitionId"] = new SelectList(_context.Competitions, "Id", "Id", game.CompetitionId);
            ViewData["Team1Id"] = new SelectList(_context.Teams.Where(t => t.Competitions.Any(c => c.Id == CompId)), "Id", "Name");
            ViewData["Team2Id"] = new SelectList(_context.Teams.Where(t => t.Competitions.Any(c => c.Id == CompId)), "Id", "Name");
            ViewBag.Id = CompId;
            ViewBag.CompetitionName = _context.Competitions.Where(c => c.Id == CompId)?.FirstOrDefault().Name;
            return View(game);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Games == null)
            {
                return NotFound();
            }

            var game = await _context.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }
            ViewData["CompetitionId"] = new SelectList(_context.Competitions, "Id", "Name", game.CompetitionId);
            ViewData["Team1Id"] = new SelectList(_context.Teams, "Id", "Name", game.Team1Id);
            ViewData["Team2Id"] = new SelectList(_context.Teams, "Id", "Name", game.Team2Id);
            ViewBag.Id = id;
            ViewBag.CompetitionName = _context.Competitions.Where(c => c.Id == game.CompetitionId)?.FirstOrDefault().Name;
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Team1Id,Team2Id,Team1Goals,Team2Goals,CompetitionId,Date,Stadium,Team1Name,Team2Name")] Game game)
        {
            var CompId = game.CompetitionId;
            var competition = _context.Competitions.Include(c => c.CompetitionTypeNavigation).Include(c => c.Teams).Where(g => g.Id == CompId).FirstOrDefault();
            var competition1 = _context.Competitions.Find(game.CompetitionId);
            if (game.Team1Id == game.Team2Id)
            {
                ModelState.AddModelError(string.Empty, "You cannot add a game between two similar teams.");
            }
            else if (competition.CompetitionTypeNavigation.Name == "Knockout")
            {
                if (_context.Games.FirstOrDefault(g => g.CompetitionId == CompId && ((g.Team1Id == game.Team1Id && g.Team2Id == game.Team2Id) || (g.Team1Id == game.Team2Id && g.Team2Id == game.Team1Id)) && g.Id != game.Id) != null)
                {
                    ModelState.AddModelError(string.Empty, "A game between these two teams already exists in this knockout competition.");
                }
                else if (game.Team1Goals == game.Team2Goals && game.Team1Goals != null && game.Team2Goals != null)
                {
                    ModelState.AddModelError(string.Empty, "You can not have ties in a knockout competition");
                }
                else if (game.Date != null && competition != null && competition.StartDate != null && competition.EndDate != null)
                {
                    if (game.Date.Value.Date < competition.StartDate.Value.Date || game.Date.Value.Date > competition.EndDate.Value.Date)
                    {
                        string dateStart = competition.StartDate.Value.Date.ToString("d", CultureInfo.InvariantCulture);
                        string dateEnd = competition.EndDate.Value.Date.ToString("d", CultureInfo.InvariantCulture);
                        ModelState.AddModelError("Date", "The game's date must be between the competition's start and end date: "
                            + dateStart + " - " + dateEnd);
                    }
                }
            }

Competition Tournament/Controllers/TeamController.cs
using Competition_Tournament.Data;
using Competition_Tournament.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Competition_Tournament.Controllers
{
    public class TeamController : Controller
    {
        private readonly CompetitionManagementContext _context; //var privata pentru clasa asta

        public TeamController(CompetitionManagementContext context) //constructorul
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? competitionId)
        {
            var teams = _context.Teams.AsQueryable();

            if (competitionId != null)
            {
                teams = teams.Where(t => t.Competitions.Any(c => c.Id == competitionId));
            }

            ViewData["Competitions"] = new SelectList(_context.Competitions, "Id", "Name");
            ViewBag.SelectedCompetitionId = competitionId;

            return View(await teams.ToListAsync());
        }

        public IActionResult Create() 
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            var team = _context.Teams.Find(id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        [HttpPost]
        public IActionResult Create(Team team)
        {
            if (team.CreatedOn > DateTime.Today)
            {
                ModelState.AddModelError("CreatedOn", "The date cannot be in the future.");
            }

            if (_context.Teams.Any(t => t.Name == team.Name))
            {
                ModelState.AddModelError("Name", "A team with this name already exists.");
            }

            if (ModelState.IsValid)
            {
                _context.Teams.Add(team);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(team);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Teams.FindAsync(id);
            if (team != null)
            {
                var players = _context.Players.Where(p => p.IdTeam == id);
                foreach (var player in players)
                {
                    // To delete the player:
                    // _context.Players.Remove(player);

                    // To disassociate the player from the team:
                    player.IdTeam = null;
                }

                _context.Teams.Remove(team);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Edit(Team team)
        {
            if (team.CreatedOn > DateTime.Today)
            {
                ModelState.AddModelError("CreatedOn", "The date cannot be in the future.");
            }

            if (_context.Teams.Any(t => t.Name == team.Name && t.Id != team.Id))
            {
                ModelState.AddModelError("Name", "A team with this name already exists.");
            }

            if (ModelState.IsValid)
            {
                _context.Entry(team).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(team);
        }
    }
}

Competition Tournament/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Competition_Tournament</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Competition_Tournament.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital@1&family=Oswald:wght@300&family=Overpass:wght@400;900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital@1&family=Oswald:wght@300&family=Overpass:wght@400;900&family=Space+Grotesk:wght@700&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3 navbar-custom">
            <div class="container-fluid">
                <a class="navbar-brand navbar-brand-custom" asp-area="" asp-controller="Home" asp-action="Index">Competition Tournament</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link nav-link-custom" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-custom" asp-area="" asp-controller="Team" asp-action="Index">Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-custom" asp-area="" asp-controller="Players" asp-action="Index">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-custom" asp-area="" asp-controller="Games" asp-action="Index">Games</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Competition_Tournament - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>