Competition Tournament/Models/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Competition_Tournament.Models;

[Table("GAME")]
public partial class Game
{
    [Key]
    public int Id { get; set; }

    [Column("Team1_Id")]
    public int? Team1Id { get; set; }

    [Column("Team2_Id")]
    public int? Team2Id { get; set; }

    [Column("Team1_Goals")]
    public int? Team1Goals { get; set; }

    [Column("Team2_Goals")]
    public int? Team2Goals { get; set; }

    [Column("Competition_Id")]
    public int? CompetitionId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string? Stadium { get; set; }

    [Column("Team1_Name")]
    [StringLength(255)]
    [Unicode(false)]
    public string? Team1Name { get; set; }

    [Column("Team2_Name")]
    [StringLength(255)]
    [Unicode(false)]
    public string? Team2Name { get; set; }

    [ForeignKey("CompetitionId")]
    [InverseProperty("Games")]
    public virtual Competition? Competition { get; set; }

    [ForeignKey("Team1Id")]
    [InverseProperty("GameTeam1s")]
    public virtual Team? Team1 { get; set; }

    [ForeignKey("Team2Id")]
    [InverseProperty("GameTeam2s")]
    public virtual Team? Team2 { get; set; }
}

Competition Tournament/Controllers/CompetitionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Competition_Tournament.Data;
using Competition_Tournament.Models;
using Competition_Tournament.Models.ViewModel;
using System.Numerics;

namespace Competition_Tournament.Controllers
{
    public class CompetitionsController : Controller
    {
        private readonly CompetitionManagementContext _context;

        public CompetitionsController(CompetitionManagementContext context)
        {
            _context = context;
        }

        // GET: Competitions
        public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        // GET: Competitions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Competitions == null)
            {
                return NotFound();
            }

            var competition = await _context.Competitions
                .Include(c => c.CompetitionTypeNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (competition == null)
            {
                return NotFound();
            }

            return View(competition);
        }

        // GET: Competitions/Create
        public IActionResult Create()
        {
            ViewData["CompetitionType"] = new SelectList(_context.CompetitionTypes, "Id", "Name");
            return View();
        }

        // POST: Competitions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,StartDate,EndDate,Location,CompetitionType,ImageFile")] Competition competition)
        {
            if (_context.Competitions.Any(c => c.Name == competition.Name))
            {
                ModelState.AddModelError("Name", "A competition with this name already exists.");
            }
            if(competition.StartDate >= competition.EndDate)
            {
                ModelState.AddModelError(string.Empty, "The end date should be grater that the start date.");
            }
            if (ModelState.IsValid)
            {
                var imageFile = competition.ImageFile;
                if (imageFile != null && imageFile.Length > 0)
                {
                    using (var stream = new MemoryStream())
                    {
                        await imageFile.CopyToAsync(stream);
                        competition.Image = stream.ToArray();
                    }
                }

                _context.Add(competition);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompetitionType"] = new SelectList(_context.CompetitionTypes, "Id", "Name", competition.CompetitionType);
            return View(competition);
        }

        // GET: Competitions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Competitions == null)
            {
                return NotFound();
            }

            var competition = await _context.Competitions.FindAsync(id);
            var teams = await _context.Teams.ToListAsync();

            if (competition == null)
            {
                return NotFound();
            }
            ViewData["CompetitionType"] = new SelectList(_context.CompetitionTypes, "Id", "Name", competition.CompetitionType);
            ViewData["Teams"] = new SelectList(teams, "Id", "Name");
            
            return View(competition);
        }

        // POST: Competitions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,StartDate,EndDate,Location,CompetitionType,ImageFile")] Competition competition)
        {
            var competitionInDb = _context.Competitions.AsNoTracking().FirstOrDefault(c => c.Name == competition.Name);
            if (competitionInDb != null && competitionInDb.Id != competition.Id)
            {
                ModelState.AddModelError("Name", "The competition name already exists.");
            }
            if (competition.StartDate >= competition.EndDate)
            {
                ModelState.AddModelError(string.Empty, "The end date should be grater that the start date.");
            }
            if (ModelState.IsValid)
                if (id != competition.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var currentCompetition = await _context.Competitions.FindAsync(id);
                    var imageFile = competition.ImageFile;
                    if (imageFile != null && imageFile.Length > 0)
                    {
                        using (var stream = new MemoryStream())
                        {
                            await imageFile.CopyToAsync(stream);
                            currentCompetition.Image = stream.ToArray();
                        }
                    }
                    else
                    {
                        currentCompetition.Image = null;
                    }
                    currentCompetition.Name = competition.Name;
                    currentCompetition.StartDate = competition.StartDate;
                    currentCompetition.EndDate = competition.EndDate;
                    currentCompetition.Location = competition.Location;
                    currentCompetition.CompetitionType = competition.CompetitionType;

                    _context.Update(currentCompetition);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompetitionExists(competition.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompetitionType"] = new SelectList(_context.CompetitionTypes, "Id", "Name", competition.CompetitionType);
            return View(competition);
        }

        // GET: Competitions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Competitions == null)
            {
                return NotFound();
            }

            var competition = await _context.Competitions
                .Include(c => c.CompetitionTypeNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (competition == null)
            {
                return NotFound();
            }

            return View(competition);
        }

        // POST: Competitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Competitions == null)
            {
                return Problem("Entity set 'CompetitionManagementContext.Competitions'  is null.");
            }
            var competition = await _context.Competitions.FindAsync(id);
            if (competition != null)
            {
                _context.Competitions.Remove(competition);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompetitionExists(int id)
        {
          return (_context.Competitions?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> AddTeam(int id)
        {
            var competition = await _context.Competitions
                .Include(c => c.Teams)
                .FirstOrDefaultAsync(m => m.Id == id);
            ICollection<Team> addedTeams = competition.Teams;
            var availableTeams = _context.Teams.Where(t => !addedTeams.Contains(t));

            TeamSelector teamSelector = new TeamSelector();
            teamSelector.Competition = competition;

            if (competition == null)
            {
                return NotFound();
            }

            ViewBag.id = competition.Id;
            ViewData["availableTeams"] = new SelectList(availableTeams, "Id", "Name");
            ViewData["addedTeams"] = new SelectList(addedTeams, "Id", "Name");

            return View(teamSelector);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTeamConfirmed(int id, TeamSelector teamSelector)
        {
            var competition = await _context.Competitions
                .Include(c => c.Teams)
                .FirstOrDefaultAsync(m => m.Id == id);
            ICollection<Team> addedTeams = competition.Teams;
            var availableTeams = _context.Teams.Where(t => !addedTeams.Contains(t));

            if (ModelState.IsValid)
            {
                var team = await _context.Teams.FindAsync(teamSelector.Team);
                if (team != null)
                {
                    competition.Teams.Add(team);
                    await _context.SaveChangesAsync();
                }
            }

            ViewBag.id = competition.Id;
            ViewData["availableTeams"] = new SelectList(availableTeams, "Id", "Name");
            ViewData["addedTeams"] = new SelectList(addedTeams, "Id", "Name");

Competition Tournament/Views/Games/Create.cshtml
@model Competition_Tournament.Models.Game

@{
    ViewData["Title"] = "Create";
}

<h1 class="display-custom">Create</h1>

<h4>Game</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-route-compid="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <h2 class="form-group-addteam-custom">@ViewBag.CompetitionName</h2>
            <div class="form-group">
                <label asp-for="Team1" class="control-label">Team1 Name</label>
                <select asp-for="Team1Id" class="form-control" asp-items="ViewBag.Team1Id" required></select>
            </div>
            <div class="form-group">
                <label asp-for="Team2" class="control-label">Team2 Name</label>
                <select asp-for="Team2Id" class="form-control" asp-items="ViewBag.Team2Id" required></select>
            </div>
            <div class="form-group">
                <label asp-for="Team1Goals" class="control-label">Team1 Goals</label>
                <input asp-for="Team1Goals" class="form-control" min="0"/>
                <span asp-validation-for="Team1Goals" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Team2Goals" class="control-label">Team2 Goals</label>
                <input asp-for="Team2Goals" class="form-control" min="0"/>
                <span asp-validation-for="Team2Goals" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stadium" class="control-label"></label>
                <input asp-for="Stadium" class="form-control" />
                <span asp-validation-for="Stadium" class="text-danger"></span>
            </div>
            <input type="hidden" name="CompId" value="@ViewBag.id" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary form-group-addteam-custom" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-secondary form-group-addteam-custom" asp-controller="Competitions" asp-action="Details" asp-route-id="@ViewBag.Id">Back to details</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Competition Tournament/Views/Games/Delete.cshtml
@model Competition_Tournament.Models.Game

@{
    ViewData["Title"] = "Delete";
}

<h1 class="display-custom">Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Game</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Team1 Goals
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team1Goals)
        </dd>
        <dt class = "col-sm-2">
            Team2 Goals
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team2Goals)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stadium)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stadium)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Competition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Competition.Name)
        </dd>
        <dt class = "col-sm-2">
            Team1 Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team1Name)
        </dd>
        <dt class = "col-sm-2">
            Team2 Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team2Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> 
        <a class="btn btn-outline-secondary" asp-action="Index">Back to List</a>
    </form>
</div>

Competition Tournament/Views/Games/Details.cshtml
@model Competition_Tournament.Models.Game

@{
    ViewData["Title"] = "Details";
}

<h1 class="display-custom">Details</h1>

<div>
    <h4>Game</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Team1 Goals
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team1Goals)
        </dd>
        <dt class = "col-sm-2">
            Team2 Goals
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team2Goals)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stadium)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stadium)
        </dd>
        <dt class = "col-sm-2">
            Competiton Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Competition.Name)
        </dd>
        <dt class = "col-sm-2">
            Team1 Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team1Name)
        </dd>
        <dt class = "col-sm-2">
            Team2 Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team2Name)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> 
    <a class="btn btn-outline-secondary" asp-action="Index">Back to List</a>
</div>

Competition Tournament/Views/Games/Edit.cshtml
@model Competition_Tournament.Models.Game

@{
    ViewData["Title"] = "Edit";
}

<h1 class="display-custom">Edit</h1>

<h4>Game</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Team1Id" class="control-label">Team1 Name</label>
                <select hidden asp-for="Team1Id" class="form-control" asp-items="ViewBag.Team1Id"></select>
                <input class="form-control" type="text" asp-for="Team1Name" readonly />
                <span asp-validation-for="Team1Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Team2Id" class="control-label">Team2 Name</label>
                <select hidden asp-for="Team2Id" class="form-control" asp-items="ViewBag.Team2Id"></select>
                <input class="form-control" type="text" asp-for="Team2Name" readonly />
                <span asp-validation-for="Team2Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Team1Goals" class="control-label">Team1 Goals</label>
                <input asp-for="Team1Goals" class="form-control" min="0" />
                <span asp-validation-for="Team1Goals" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Team2Goals" class="control-label">Team2 Goals</label>
                <input asp-for="Team2Goals" class="form-control" min="0" />
                <span asp-validation-for="Team2Goals" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompetitionId" class="control-label">Competition Name</label>
                <select hidden asp-for="CompetitionId" class="form-control" asp-items="ViewBag.CompetitionId"></select>
                <input class="form-control" type="text" value="@ViewBag.CompetitionName" readonly />
                <span asp-validation-for="CompetitionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stadium" class="control-label"></label>
                <input asp-for="Stadium" class="form-control" />
                <span asp-validation-for="Stadium" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-primary form-group-addteam-custom" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-secondary form-group-addteam-custom" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Competition Tournament/Views/Games/Index.cshtml
@model IEnumerable<Competition_Tournament.Models.Game>

@{
    ViewData["Title"] = "Index";
}

<h1 class="display-custom">Games</h1>
<!--
<p>
    <a asp-action="Create">Create New</a>
</p>
-->

<form method="get">
    <label for="competitionId"><b>Competition:</b></label>
    <select id="competitionId" name="competitionId" onchange="this.form.submit()">
        <option value="">All</option>
        @foreach (var item in ViewBag.Competitions)
        {
            var selected = item.Value == Context.Request.Query["competitionId"];
            <option value="@item.Value" selected="@selected">@item.Text</option>
        }
    </select>
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stadium)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Competition)
            </th>
            <th>
                Team1 Name
            </th>
            <th>
                Team2 Name
            </th>
            <th>
                Team1 Goals
            </th>
            <th>
                Team2 Goals
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stadium)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Competition.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Team1Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Team2Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Team1Goals)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Team2Goals)
            </td>
            <td>
                <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@item.Id">Details</a>
                <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>