Competition Tournament/Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Competition_Tournament.Models;

[Table("TEAM")]
public partial class Team
{
    [Key]
    public int Id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string? Name { get; set; }

    [Column("Award_Nr")]
    public int? AwardNr { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string? Motto { get; set; }

    [Column("Created_On", TypeName = "date")]
    [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
    public DateTime? CreatedOn { get; set; }

    [InverseProperty("Team1")]
    public virtual ICollection<Game> GameTeam1s { get; set; } = new List<Game>();

    [InverseProperty("Team2")]
    public virtual ICollection<Game> GameTeam2s { get; set; } = new List<Game>();

    [InverseProperty("IdTeamNavigation")]
    public virtual ICollection<Player> Players { get; set; } = new List<Player>();

    [ForeignKey("TeamId")]
    [InverseProperty("Teams")]
    public virtual ICollection<Competition> Competitions { get; set; } = new List<Competition>();
}

Competition Tournament/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Competition_Tournament.Data;
using Competition_Tournament.Models;

namespace Competition_Tournament.Controllers
{
    public class PlayersController : Controller
    {
        private readonly CompetitionManagementContext _context;

        public PlayersController(CompetitionManagementContext context)
        {
            _context = context;
        }

        // GET: Index
        public async Task<IActionResult> Index(int? id)
        {
            IQueryable<Player> players = _context.Players.Include(p => p.IdTeamNavigation);

            if (id != null)
            {
                players = players.Where(p => p.IdTeam == id);
            }   

            ViewData["Teams"] = new SelectList(_context.Teams, "Id", "Name");
            ViewBag.SelectedTeamId = id;

            return View(await players.ToListAsync());
        }

        // GET: Index
        public async Task<IActionResult> Index1(int? id)
        {
            IQueryable<Player> players = _context.Players.Include(p => p.IdTeamNavigation);

            if (id != null)
            {
                players = players.Where(p => p.IdTeam == id);
            }

            ViewData["Teams"] = new SelectList(_context.Teams, "Id", "Name");
            ViewBag.SelectedTeamId = id;

            return View(await players.ToListAsync());
        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Players == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .Include(p => p.IdTeamNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            ViewData["IdTeam"] = new SelectList(_context.Teams, "Id", "Name");
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Age,IdTeam")] Player player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdTeam"] = new SelectList(_context.Teams, "Id", "Name", player.IdTeam);
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Players == null)
            {
                return NotFound();
            }

            var player = await _context.Players.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            ViewData["IdTeam"] = new SelectList(_context.Teams, "Id", "Name", player.IdTeam);
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Age,IdTeam")] Player player)
        {
            if (id != player.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdTeam"] = new SelectList(_context.Teams, "Id", "Name", player.IdTeam);
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Players == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .Include(p => p.IdTeamNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Players == null)
            {
                return Problem("Entity set 'CompetitionManagementContext.Players'  is null.");
            }
            var player = await _context.Players.FindAsync(id);
            if (player != null)
            {
                _context.Players.Remove(player);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
          return (_context.Players?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Competition Tournament/Controllers/TeamController.cs
using Competition_Tournament.Data;
using Competition_Tournament.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Competition_Tournament.Controllers
{
    public class TeamController : Controller
    {
        private readonly CompetitionManagementContext _context; //var privata pentru clasa asta

        public TeamController(CompetitionManagementContext context) //constructorul
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? competitionId)
        {
            var teams = _context.Teams.AsQueryable();

            if (competitionId != null)
            {
                teams = teams.Where(t => t.Competitions.Any(c => c.Id == competitionId));
            }

            ViewData["Competitions"] = new SelectList(_context.Competitions, "Id", "Name");
            ViewBag.SelectedCompetitionId = competitionId;

            return View(await teams.ToListAsync());
        }

        public IActionResult Create() 
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            var team = _context.Teams.Find(id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        [HttpPost]
        public IActionResult Create(Team team)
        {
            if (team.CreatedOn > DateTime.Today)
            {
                ModelState.AddModelError("CreatedOn", "The date cannot be in the future.");
            }

            if (_context.Teams.Any(t => t.Name == team.Name))
            {
                ModelState.AddModelError("Name", "A team with this name already exists.");
            }

            if (ModelState.IsValid)
            {
                _context.Teams.Add(team);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(team);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Teams.FindAsync(id);
            if (team != null)
            {
                var players = _context.Players.Where(p => p.IdTeam == id);
                foreach (var player in players)
                {
                    // To delete the player:
                    // _context.Players.Remove(player);

                    // To disassociate the player from the team:
                    player.IdTeam = null;
                }

                _context.Teams.Remove(team);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Edit(Team team)
        {
            if (team.CreatedOn > DateTime.Today)
            {
                ModelState.AddModelError("CreatedOn", "The date cannot be in the future.");
            }

            if (_context.Teams.Any(t => t.Name == team.Name && t.Id != team.Id))
            {
                ModelState.AddModelError("Name", "A team with this name already exists.");
            }

            if (ModelState.IsValid)
            {
                _context.Entry(team).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(team);
        }
    }
}

Competition Tournament/Views/Team/Create.cshtml
@model Competition_Tournament.Models.Team

@{
    ViewData["Title"] = "Create";
}

<h1 class="display-custom">Create</h1>

<h4>Team</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AwardNr" class="control-label">Award Nr</label>
                <input asp-for="AwardNr" class="form-control" min="0" required />
                <span asp-validation-for="AwardNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Motto" class="control-label"></label>
                <input asp-for="Motto" class="form-control" required />
                <span asp-validation-for="Motto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label">Created On</label>
                <input asp-for="CreatedOn" class="form-control" type="date" max="@DateTime.Today.ToString("yyyy-MM-dd")" required />
                <span asp-validation-for="CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary form-group-addteam-custom" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-secondary form-group-addteam-custom" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Competition Tournament/Views/Team/Delete.cshtml
@model Competition_Tournament.Models.Team

@{
    ViewData["Title"] = "Delete";
}

<h1 class="display-custom">Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Team</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Award Nr
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AwardNr)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Motto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Motto)
        </dd>
        <dt class="col-sm-2">
            Created On
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> 
        <a class="btn btn-outline-secondary" asp-action="Index">Back to List</a>
    </form>
</div>

Competition Tournament/Views/Team/Edit.cshtml
@model Competition_Tournament.Models.Team

@{
    ViewData["Title"] = "Edit";
}

<h1 class="display-custom">Edit</h1>

<h4>Team</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" required/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AwardNr" class="control-label">Award Nr</label>
                <input asp-for="AwardNr" class="form-control" min="0" required/>
                <span asp-validation-for="AwardNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Motto" class="control-label"></label>
                <input asp-for="Motto" class="form-control" required/>
                <span asp-validation-for="Motto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label">Created On</label>
                <input asp-for="CreatedOn" class="form-control" required type="date" max="@DateTime.Today.ToString("yyyy-MM-dd")" />
                <span asp-validation-for="CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-primary form-group-addteam-custom" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-secondary form-group-addteam-custom" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Competition Tournament/Views/Team/Index.cshtml
@model IEnumerable<Competition_Tournament.Models.Team>

@{
    ViewData["Title"] = "View";
}

<h1 class="display-custom">Teams</h1>

<div class="container2">
    <p>
        <a class="create-custom" asp-action="Create">Create New</a>
    </p>

    <form class="margin-left" method="get">
        <label for="competitionId"><b>Competition:</b></label>
        <select id="competitionId" name="competitionId" onchange="this.form.submit()">
            <option value="">All</option>
            @foreach (var item in ViewBag.Competitions)
            {
                var selected = item.Value == ViewBag.SelectedCompetitionId?.ToString();
                <option value="@item.Value" selected="@selected">@item.Text</option>
            }
        </select>
    </form>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Award Nr
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Motto)
            </th>
            <th>
                Created On
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AwardNr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Motto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td>
                    <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                    <a class="btn btn-outline-primary" asp-controller="Players" asp-action="Index1" asp-route-id="@item.Id">Details</a> 
                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>